version: '3.2'

services:
  app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    tty: true
    container_name: ${COMPOSE_PROJECT_NAME}_app
    hostname: app
    working_dir: /var/www/html
    expose:
      - 9000
    volumes:
      - ./:/var/www/html:cached
      - ./:/var/run/php-fpm/
      - ./docker/config/xdebug.ini:/etc/php-7.4.d/15-xdebug.ini
    links:
      - database
  nginx:
    image: nginx:1.19.0
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    tty: true
    expose:
      - "80"
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html:cached
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/config/conf.d/:/etc/nginx/conf.d/
      - ./docker/logs:/var/log/nginx/
    depends_on:
      - app

  # The Database
  database:
    image: mysql:5.7
    container_name: ${COMPOSE_PROJECT_NAME}_db
    platform: linux/x86_64
    volumes:
      - ./docker/mysql_data:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=app_db"
      - "MYSQL_PASSWORD=password"
      - "MYSQL_ROOT_PASSWORD=password"
    expose:
      - "3306"
    ports:
      - 3306:3306

  # Frontend
  frontend:
    build:
      context: ./docker
      dockerfile: ./Dockerfile.node
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    depends_on:
      - "app"
    command: "tail -f /dev/null"
